
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox;
	
	private global::Gtk.DrawingArea canvas;
	
	private global::Gtk.Button runbutton;
	
	private global::Gtk.Button loadButton;
	
	private global::Gtk.Button loadSavedWorld;
	
	private global::Gtk.Statusbar statusbar;
	
	private global::Gtk.Label statusLabel;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox = new global::Gtk.VBox ();
		this.vbox.Name = "vbox";
		this.vbox.Spacing = 6;
		// Container child vbox.Gtk.Box+BoxChild
		this.canvas = new global::Gtk.DrawingArea ();
		this.canvas.Name = "canvas";
		this.vbox.Add (this.canvas);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox [this.canvas]));
		w1.Position = 0;
		// Container child vbox.Gtk.Box+BoxChild
		this.runbutton = new global::Gtk.Button ();
		this.runbutton.CanFocus = true;
		this.runbutton.Name = "runbutton";
		this.runbutton.UseUnderline = true;
		this.runbutton.Label = global::Mono.Unix.Catalog.GetString ("Run!");
		this.vbox.Add (this.runbutton);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox [this.runbutton]));
		w2.Position = 1;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox.Gtk.Box+BoxChild
		this.loadButton = new global::Gtk.Button ();
		this.loadButton.CanFocus = true;
		this.loadButton.Name = "loadButton";
		this.loadButton.UseUnderline = true;
		this.loadButton.Label = global::Mono.Unix.Catalog.GetString ("Load Saved Top");
		this.vbox.Add (this.loadButton);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox [this.loadButton]));
		w3.Position = 2;
		w3.Expand = false;
		w3.Fill = false;
		// Container child vbox.Gtk.Box+BoxChild
		this.loadSavedWorld = new global::Gtk.Button ();
		this.loadSavedWorld.CanFocus = true;
		this.loadSavedWorld.Name = "loadSavedWorld";
		this.loadSavedWorld.UseUnderline = true;
		this.loadSavedWorld.Label = global::Mono.Unix.Catalog.GetString ("Load Saved World");
		this.vbox.Add (this.loadSavedWorld);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox [this.loadSavedWorld]));
		w4.Position = 3;
		w4.Expand = false;
		w4.Fill = false;
		// Container child vbox.Gtk.Box+BoxChild
		this.statusbar = new global::Gtk.Statusbar ();
		this.statusbar.Name = "statusbar";
		this.statusbar.Spacing = 6;
		// Container child statusbar.Gtk.Box+BoxChild
		this.statusLabel = new global::Gtk.Label ();
		this.statusLabel.Name = "statusLabel";
		this.statusLabel.Xpad = 6;
		this.statusLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Not Started");
		this.statusbar.Add (this.statusLabel);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.statusbar [this.statusLabel]));
		w5.Position = 1;
		w5.Expand = false;
		w5.Fill = false;
		this.vbox.Add (this.statusbar);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox [this.statusbar]));
		w6.Position = 4;
		w6.Expand = false;
		w6.Fill = false;
		this.Add (this.vbox);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 646;
		this.DefaultHeight = 391;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.runbutton.Clicked += new global::System.EventHandler (this.OnRunbuttonClicked);
		this.loadButton.Clicked += new global::System.EventHandler (this.OnLoadTopButtonClicked);
		this.loadSavedWorld.Clicked += new global::System.EventHandler (this.OnLoadSavedWorldClicked);
	}
}
